#!/bin/sh

# mingw32-build - mingw32 build for libtorsion
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion

ARCH=${1:-x86_64}
WIN32_LIBS='-lkernel32 -luser32 -ladvapi32 -liphlpapi -lpsapi -lbcrypt'
SHARED_FLAGS='-Wl,--out-implib,libtorsion.dll.a -Wl,--output-def,libtorsion.def'

exec make -f Makefile.unix CC=$ARCH-w64-mingw32-cc         \
                           AR=$ARCH-w64-mingw32-ar         \
                           RANLIB=$ARCH-w64-mingw32-ranlib \
                           ARFLAGS=cr                      \
                           SHARED_SUFFIX=.dll              \
                           EXE_SUFFIX=.exe                 \
                           SHARED="-shared $SHARED_FLAGS"  \
                           LIBS="$WIN32_LIBS $LIBS"        \
                           all libtorsion.dll
