#!/bin/sh

# mingw32-configure - mingw32 wrapper for configure scripts
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion
#
# Partially based on:
#   https://github.com/jedisct1/libsodium/blob/master/dist-build/msys2-win64.sh

set -e

. "`dirname "$0"`/mingw32-env"

CONFIGURE="$1"

test -x "$CONFIGURE"

shift

mkdir -p "$PREFIX"

exec "$CONFIGURE" --prefix="$PREFIX"      \
                  --exec-prefix="$PREFIX" \
                  --host="$MINGW_TARGET"  \
                  "$@"
