#!/bin/sh

# wasi-make - wasi wrapper for makefiles
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion

set -e

DIR=`dirname "$0"`
MAKE=$1

source "$DIR/wasi-env"

shift

mkdir -p "$PREFIX"

exec "$MAKE" "$@"
