#!/bin/sh

# wasi-configure - wasi wrapper for configure scripts
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion
#
# Partially based on:
#   https://github.com/jedisct1/libsodium/blob/master/dist-build/wasm32-wasi.sh

set -e

. "`dirname "$0"`/wasi-env"

CONFIGURE="$1"

test -x "$CONFIGURE"

shift

mkdir -p "$PREFIX"

BUILDDIR=.

if test -d ./build-aux; then
  BUILDDIR=./build-aux
fi

if test -f $BUILDDIR/config.sub; then
  if ! grep -F -q 'wasi' $BUILDDIR/config.sub; then
    cp -f "$WASI/share/misc/config.guess" $BUILDDIR/config.guess
    cp -f "$WASI/share/misc/config.sub" $BUILDDIR/config.sub
  fi
fi

exec "$CONFIGURE" --prefix="$PREFIX"             \
                  --with-sysroot="$WASI_SYSROOT" \
                  --host="$WASI_TARGET"          \
                  "$@"
