#!/bin/sh

# wasi-make - wasi wrapper for makefiles
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion

set -e

. "`dirname "$0"`/wasi-env"

MAKE="$1"

shift

mkdir -p "$PREFIX"

exec "$MAKE" "$@"
