#!/bin/sh

# wasi-env - wasi environment for make
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion
#
# Partially based on:
#   https://github.com/jedisct1/libsodium/blob/master/dist-build/wasm32-wasi.sh

if test -n "$WASI_SDK"; then
  echo > /dev/null
elif test -d /opt/wasi-sdk; then
  WASI_SDK=/opt/wasi-sdk
elif test -d /opt/local/wasi-sdk; then
  WASI_SDK=/opt/local/wasi-sdk
elif test -d "$HOME/wasi-sdk"; then
  WASI_SDK="$HOME/wasi-sdk"
else
  echo 'WASI SDK not found!' >& 2
  exit 1
fi

export WASI="$WASI_SDK"
export TARGET='wasm32-wasi'
export SYSROOT="$WASI_SDK/share/wasi-sysroot"
export PREFIX="`pwd`/$TARGET"
export PATH="$WASI_SDK/bin:$PATH"
export CC='clang'
export CXX='clang++'
export LD='wasm-ld'
export NM='llvm-nm'
export AR='llvm-ar'
export RANLIB='llvm-ranlib'
export STRIP='llvm-strip'
export CFLAGS="--target=$TARGET --sysroot=$SYSROOT"
export LDFLAGS='-Wl,--no-threads'
