#!/bin/sh

# wasi-env - wasi environment for configure/make
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion
#
# Partially based on:
#   https://github.com/jedisct1/libsodium/blob/master/dist-build/wasm32-wasi.sh

if test -n "$WASI"; then
  WASI=`cd "$WASI" && pwd`
elif test -d /opt/wasi-sdk; then
  WASI=/opt/wasi-sdk
elif test -d /opt/local/wasi-sdk; then
  WASI=/opt/local/wasi-sdk
else
  echo 'WASI SDK not found!' >& 2
  exit 1
fi

WASI_TARGET='wasm32-wasi'
WASI_SYSROOT="$WASI/share/wasi-sysroot"
WASI_FLAGS="--target=$WASI_TARGET --sysroot=$WASI_SYSROOT"

export WASI="$WASI"
export PREFIX="`pwd`/$WASI_TARGET"
export PATH="$WASI/bin:$PATH"
export CC='clang'
export CXX='clang++'
export AS='clang'
export LD='wasm-ld'
export NM='llvm-nm -B'
export AR='llvm-ar'
export ARFLAGS='cr'
export RANLIB='llvm-ranlib'
export STRIP='llvm-strip'
export OBJDUMP='llvm-objdump'
export CFLAGS="$WASI_FLAGS $CFLAGS"
export CXXFLAGS="$WASI_FLAGS -std=c++11 $CXXFLAGS"
export ASFLAGS="$WASI_FLAGS $ASFLAGS"
export LDFLAGS="$LDFLAGS"
