#!/bin/sh

# wasi-configure - wasi wrapper for configure scripts
# Copyright (c) 2020, Christopher Jeffrey (MIT License).
# https://github.com/bcoin-org/libtorsion

set -e

DIR=`dirname "$0"`
CONFIGURE=$1

source "$DIR/wasi-env"

shift

mkdir -p "$PREFIX"

cp -f "$WASI_SDK/share/misc/config.guess" "$DIR/../build-aux/config.guess"
cp -f "$WASI_SDK/share/misc/config.sub" "$DIR/../build-aux/config.sub"

exec "$CONFIGURE" --prefix="$PREFIX"                            \
                  --with-sysroot="$WASI_SDK/share/wasi-sysroot" \
                  --host=wasm32-wasi                            \
                  "$@"
