#!/bin/sh

set -e

CMAKE=$1
DIR=`dirname "$0"`

shift

if test -n "$WASI_SDK"; then
  echo > /dev/null
elif test -d /opt/wasi-sdk; then
  WASI_SDK=/opt/wasi-sdk
elif test -d /opt/local/wasi-sdk; then
  WASI_SDK=/opt/local/wasi-sdk
elif test -d "$HOME/wasi-sdk"; then
  WASI_SDK="$HOME/wasi-sdk"
else
  echo 'WASI SDK not found!' >& 2
  exit 1
fi

exec "$CMAKE" -G 'Unix Makefiles'                                           \
              -DCMAKE_TOOLCHAIN_FILE="$WASI_SDK/share/cmake/wasi-sdk.cmake" \
              -DWASI_SDK_PREFIX="$WASI_SDK"                                 \
              "$@"
